### ISSUE TITLE
The question about using get_random_pose functions to train zero123 cannot train a complete object

### ISSUE THREAD

**Issue by hrz2000** [TAU-VAILab/Vox-E#10]
I want to introduce zero123 into this library and use this function to obtain the pose,
```
def get_random_pose(
    radius: float, device=torch.device("cpu")
) -> CameraPose:
    rand_pitch = float(np.random.rand(1) * 90.0)
    rand_yaw = float(np.random.rand(1) * 360.0)
    c2w = _translate_z(radius, device)
    c2w = _rotate_pitch(rand_pitch / 180.0 * np.pi, device) @ c2w
    c2w = _rotate_yaw(rand_yaw / 180.0 * np.pi, device) @ c2w

    # get dir
    dir = 'front'
    if (rand_yaw > 45.0) and (rand_yaw < 315.0):
        dir = 'side'
    if (rand_yaw > 120.0) and (rand_yaw < 240.0):
        dir = 'back'
    if rand_pitch < 25.0:
        dir = 'overhead'

    return CameraPose(rotation=c2w[:3, :3], translation=c2w[:3, 3:]), dir, rand_pitch, rand_yaw
```
With pitch=60, azimuth=0, HEMISPHERICAL_RADIUS_CONSTANT=4.0311 is used as the position parameter of the input image and the corresponding pose is obtained, optimization from other views using the above functions to obtain a pose, but I found that training cannot produce a complete thing, and its trend is to have a reference image from different perspectives.
For your convenience, after fixing the pitch and radius, I selected 8 perspectives for rgb supervision to obtain the rendering results.
![image](https://github.com/TAU-VAILab/Vox-E/assets/79900945/693de93b-1350-4132-a581-1782e8486a74)
I have limited knowledge of nerf, especially based on voxel, I tried to change some parameters but failed, such as changing the grid_dims from 160 to 20, changing the initial density and feature of VoxelGrid, etc., what parameters should I adjust? Looking forward to your answer, it's important to me, thank you very much!

**Comment by etaisella** [comment]
Hi and thanks for your interest.
Unfortunately I don't know the format zero123 expects as input for poses.
I can say though that I don't think changing the grid dimensions of the grid will change anything, reducing the grid size will just result in a less detailed reconstruction.
If it helps, I closed an issue regarding using blender to extract poses from meshes, maybe looking there will help you figure out how the poses should look.

**Comment by hrz2000** [comment]
tks for your kindly reply！
