### ISSUE TITLE
Bug fix in `thre3d_reprs/reders.py`

### ISSUE THREAD

**Issue by Andreus00** [TAU-VAILab/Vox-E#12]
Hi, I wanted to report a bug.
I ran the `train_sh_based_voxel_grid_with_posed_images.py` script and found this error:
`sample_aabb_bound_uniform_points_on_rays() got an unexpected keyword argument 'linear_disparity_sampling'`.
It looks like at line 71 of `thre3d_reprs/reders.py` the kwarg `linear_disparity_sampling` is being passed to the `sample_aabb_bound_uniform_points_on_rays` even if it does not accept it.
I removed that line and the code runs flawlessly.

**Comment by etaisella** [comment]
Thank you very much for this, we have deleted the line in mention from our repo.
