### ISSUE TITLE
Is there a way to export the 3d model as a .obj or .glb file?

### ISSUE THREAD

**Issue by Frklin** [TAU-VAILab/Vox-E#13]
Hi,
great work btw, i would like to know if there is a way to have the edited object as a .obj file.

**Comment by etaisella** [comment]
Hi and thank you for your interest in Vox-E!
Unfortunately we currently do not have code for saving the edited object as an .obj or .glb file. I'm assuming you're asking if we have code for turning our products in to meshes, that might be possible with marching cubes but as for now we do not have plans to incorporate this into our code, sorry!
