### ISSUE TITLE
hello, thanks for your work, since you show the results of real word scene, could you please provide the real word datasets and the usage guideline of it. 

### ISSUE THREAD

**Issue by StellarCheng** [TAU-VAILab/Vox-E#3]

**Comment by etaisella** [comment]
Hi and thank you for your interest in Vox-E :)
The real world scenes shown in the paper can be found [here](https://drive.google.com/file/d/18hxar-OXpHA_SuX2pYsVkad0sltdK5GK/view?usp=sharing).
As for usage guidelines (by example), first reconstruct the pinecone scene with:
bash bash_scripts/real_scenes/train_default_relu_field_real.sh -d pinecone
Then run the edit demo script:
bash bash_scripts/real_scenes/edit_demo_real.sh

A quick look at the scripts will hopefully be enough to guide you through making other edits or working on the other (flowers) scene.

I hope this helps, and be sure that this information will be added to the README soon.
