### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by LordLiang** [TAU-VAILab/Vox-E#6]
Thanks for excellent work!
My GPU Memory is just 12G. Can I run this project successfully? If yes, what parameter should I change?

**Comment by etaisella** [comment]
Hi and thanks for your interest in Vox-E :)
To reduce GPU memory usage you can reduce "train_num_samples_per_ray" and "render_num_samples_per_ray".
These are parameters in both "train_sh_based_voxel_grid_with_posed_images.py" and "edit_pretrained_relu_field.py".
Take into consideration that this might produce worse results than those shown in the paper.
Let me know if this helps!

**Comment by LordLiang** [comment]
> Hi and thanks for your interest in Vox-E :) To reduce GPU memory usage you can reduce "train_num_samples_per_ray" and "render_num_samples_per_ray". These are parameters in both "train_sh_based_voxel_grid_with_posed_images.py" and "edit_pretrained_relu_field.py". Take into consideration that this might produce worse results than those shown in the paper. Let me know if this helps!

Thanks!
