### ISSUE TITLE
Question about evaluation metrics script

### ISSUE THREAD

**Issue by colorful-liyu** [TAU-VAILab/Vox-E#7]
Hi, thanks for your great work.
May I ask when the evaluation metrics script will release? 
I hope to adopt the metrics you proposed for my work, such as `CLIP_Sim`, `CLIP_dir`, `FID_Rec`, `FID_Input`.

**Comment by etaisella** [comment]
Hi and thanks for your interest in Vox-E :)
The evaluation metrics script is actually already released, you can find it in evaluation/calculate_metrics.py.
You can see exactly how the metrics are calculated by looking through the script.
You need to arrange your results in a particular structure if you want to actually use the script, I suggest modifying the script slightly to match your setting.
Hope this helps, if it doesn't - feel free to open another issue.
