### ISSUE TITLE
About the use of evaluation indicator scripts

### ISSUE THREAD

**Issue by hrz2000** [TAU-VAILab/Vox-E#9]
![image](https://github.com/TAU-VAILab/Vox-E/assets/79900945/ee8b029b-f961-431c-816a-961dd05ad413)
How were these folders obtained? is there a complete demo for use of evaluation/calculation_metrics.py ?

**Comment by etaisella** [comment]
Hi and thank you for your interest in our work :)
Unfortunately we do not have a demo for using the calculate_metrics.py script. However it is pretty simple to use, just follow these steps:
1. Make a folder for a certain scene (for example the 'dog2' scene).
2. Put the reconstruction inputs (i.e. data/dog2/train) in '\<scene dir\>/inputs'.
3. After reconstructing the scene (with the train_sh_based_voxel_grid_with_posed_images.py script), you need to render images of the reconstruction and place them in '\<scene dir\>/recon'. Additionally, you also need to create a prompt.txt file which has a description of the **original scene** (i.e. "a render of a dog") and place that also in the '\<scene dir\>/recon' folder. You can do both of these things by using the render_sh_based_voxel_grid.py script. Just give it the reconstructed model as input, set the output folder to the '\<scene dir\>/recon' folder, use the -p \<reconstruction prompt\> flag (it will create the prompt.txt file, and finally use the --save_freq argument to make the script also output 2d images of the scene (if I recall correctly we use --save_freq 10 in our experiments).
4. After editing the scene you need to repeat step 3 for the edited scene, this time the artifacts need to go into a '\<scene dir\>/\<edit name\>' dir (i.e. dog2/party_hat). For this you can again use either the render_sh_based_voxel_grid.py script (global edits) or render_sh_based_voxel_grid_attn.py (local edits) with the appropriate arguments (for instance here you would want to use something like -p "a render of a dog wearing a party hat" --save_freq 10).  

Hope this helps.
